FROM node:18-buster

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --legacy-peer-deps

COPY . ./

ARG SITE_URL
ARG UTTERANCES_REPOSITORY
ARG NETLIFY_CMS_BACKEND_REPO
ARG NETLIFY_CMS_BACKEND_BRANCH
ARG TARGET_REPO_BRANCH_CONTRIBUTION

ENV SITE_URL $SITE_URL
ENV GATSBY_SITE_URL $SITE_URL
ENV UTTERANCES_REPOSITORY $UTTERANCES_REPOSITORY
ENV GATSBY_UTTERANCES_REPOSITORY $UTTERANCES_REPOSITORY
ENV NETLIFY_CMS_BACKEND_REPO $NETLIFY_CMS_BACKEND_REPO
ENV GATSBY_NETLIFY_CMS_BACKEND_REPO $NETLIFY_CMS_BACKEND_REPO
ENV NETLIFY_CMS_BACKEND_BRANCH $NETLIFY_CMS_BACKEND_BRANCH
ENV GATSBY_NETLIFY_CMS_BACKEND_BRANCH $NETLIFY_CMS_BACKEND_BRANCH
ENV TARGET_REPO_BRANCH_CONTRIBUTION $TARGET_REPO_BRANCH_CONTRIBUTION
ENV GATSBY_TARGET_REPO_BRANCH_CONTRIBUTION $TARGET_REPO_BRANCH_CONTRIBUTION

RUN npm run build

CMD npm run serve
