FROM node:14-buster

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . ./

ARG GOOGLE_TAG_MANAGER_ID
ARG SITE_URL
ARG NETLIFY_CMS_BACKEND_REPO
ARG NETLIFY_CMS_BACKEND_BRANCH

ENV GOOGLE_TAG_MANAGER_ID $GOOGLE_TAG_MANAGER_ID
ENV SITE_URL $SITE_URL
ENV NETLIFY_CMS_BACKEND_REPO $NETLIFY_CMS_BACKEND_REPO
ENV NETLIFY_CMS_BACKEND_BRANCH $NETLIFY_CMS_BACKEND_BRANCH

RUN npm run build

CMD npm run serve
